volumes:
  pgdata:

services:
  db:
    image: postgres:15.15-alpine
    container_name: mypostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: myfastapi
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    ports:
      - "8080:8080"
